name: Build Workflow

on:
    push:
        branches: dev

jobs:
    check_project_compilation_and_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore Osu-maps/

            - name: Build the project
              run: dotnet build --no-restore Osu-maps/

            - name: Run tests with code coverage
              run: dotnet test --collect:"XPlat Code Coverage" Osu-maps/ --no-build
            
            - name: Find coverage file
              id: coverage
              run: |
                echo "##[group]Locate coverage file"
                FILE=$(find Osu-maps/TestResults -name 'coverage.cobertura.xml' | head -n 1)
                echo "Found coverage file: $FILE"
                echo "coverage_file=$FILE" >> $GITHUB_OUTPUT
                echo "##[endgroup]"
            
            - name: Upload code coverage results
              uses: codecov/codecov-action@v2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ${{ steps.coverage.outputs.coverage_file }}
                fail_ci_if_error: true